openapi: 3.0.0

info:
  title: OpenAPI specification documentation for WxSAPIntegration
  version: "1.0"
  contact:
    name: Kalpshekhar Gupta
    url: https://github.com/kalpshekhar-sag

servers:
  - url: http://localhost:5555/wxsapintegration

paths:
  /customers:
    get:
      tags:
        - customers
      summary: Get all the customers
      description: Uses behind the scenes  BAPI_CUSTOMER_GETLIST to get IDs and then BAPI_CUSTOMER_GETDETAIL2 to get details. Pagination is supported when pageNumber and pageSize paramters are used. Otherwise, all customers are fetched.
      parameters:
        - name: pageNumber
          in: query
          description: Page number and it begins from 0.
          required: false
          schema:
            type: string
            example: 0
        - name: pageSize
          in: query
          description: Number of records per page.
          required: false
          schema:
            type: string
            example: 50
      responses:
        "200":
          description: Success
          content:
            "application/json":
              schema:
                type: object
                properties:
                  response:
                    type: object
                    properties:
                      customers:
                        type: array
                        items:
                          type: object
                      message:
                        type: string
                        

  /customers/{id}:
    get:
      tags:
        - customers
      summary: Get customer by id
      description: Get customer by id using BAPI_CUSTOMER_GETDETAIL2
      responses:
        "200":
          description: Customer details
          content:
            "application/json":
              schema:
                type: object
                properties:
                  response:
                    type: object
                  message:
                    type: string

    parameters:
      - name: id
        in: path
        description: ID of a customer
        required: true
        schema:
          type: string
        example:
          "0000001400"

  /customers/search:
    post:
      tags:
        - customers
      summary: Search customers
      description: Search cutsomer using BAPI_CUSTOMER_GETLIST
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              properties:
                request:
                  type: object
                  properties:
                    IDRANGE:
                      type: array
                      items:
                        type: object
                        properties:
                          SIGN:
                            type: string
                          OPTION:
                            type: string
                          LOW:
                            type: string
                          HIGH:
                            type: string
            example:
              "request": {"IDRANGE": [{"SIGN": "I","OPTION": "BT","LOW": "0000001400","HIGH": "0000002000"}]}
      responses:
        "200":
          description: Success
          content:
            "application/json":
              schema:
                type: object
                properties:
                  response:
                    type: object
                    properties:
                      customers:
                        type: array
                        items:
                          type: object
                  message:
                    type: string
           

  /equipments:
    get:
      tags:
        - equipments
      summary: Get all equipments
      description: Get all equipments using BAPI_EQUI_GETLIST
      responses:
        "200":
          description: Success
          content:
            "application/json":
              schema:
                type: object
                properties:
                  response:
                    type: object
                    properties:
                      equipments:
                        type: array
                        items:
                          type: object
                  message:
                    type: string


  /equipments/{id}:
    get:
      tags:
        - equipments
      summary: Get equipment by id
      description: Get equipment by id using BAPI_EQUI_GETDETAIL
      responses:
        "200":
          description: Equipment details
          content:
            "application/json":
              schema:
                type: object
                properties:
                  response:
                    type: object
                  message:
                    type: string
    parameters:
      - name: id
        in: path
        description: Id of the equipment
        required: true
        schema:
          type: string
        example:
          "000000000010000466"

  /equipments/search:
    post:
      tags:
        - equipments
      summary: Search equipments
      description: Search equipments using BAPI_EQUI_GETLIST
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              properties:
                request:
                  type: object
                  properties:
                    MAINPLANT_RA:
                      type: array
                      items:
                        type: object
                        properties:
                          SIGN:
                            type: string
                          OPTION:
                            type: string
                          LOW:
                            type: string
                          HIGH:
                            type: string
            example:
              "request": {"MAINPLANT_RA": [{"SIGN": "I","OPTION": "BT","LOW": "1000","HIGH": "1200"}]}
      responses:
        "200":
          description: Success
          content:
            "application/json":
              schema:
                type: object
                properties:
                  response:
                    type: object
                    properties:
                      equipments:
                        type: array
                        items:
                          type: object
                  message:
                    type: string

  /salesorders/search:
    post:
      tags:
        - salesorders
      summary: Search sales orders
      description: Search sales orders using BAPI_SALESORDER_GETLIST
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              properties:
                  request:
                    type: object
                    properties:
                      CUSTOMER_NUMBER:
                        type: string
            example:
              "request": {"CUSTOMER_NUMBER": "0000001400"}
      responses:
        "200":
          description: Success
          content:
            "application/json":
              schema:
                type: object
                properties:
                  response:
                    type: object
                    properties:
                      salesOrders:
                        type: array
                        items:
                          type: object
                      message:
                        type: string

  /salesorders:
    post:
      tags: 
        - salesorders
      summary: Create sales order
      description: Create sales order using BAPI_SALESORDER_CREATEFORMDAT2.
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              properties:
                request:
                  type: object
                  properties:
                    organizationalData:
                      type: object
                      properties: 
                        salesOrganization:
                          type: string
                        distributionChannel:
                          type: string
                        division:
                          type: string
                    customerNumber:
                      type: string
                    items:
                      type: array
                      items:
                        type: object
                        properties: 
                          number:
                            type: string
                          material:
                            type: string
                          plant:
                            type: string
                          quantity:
                            type: string
                          category:
                            type: string
                          schedules:
                            type: array
                            items:
                              type: object
                              properties:
                                line:
                                  type: string
                                quantity:
                                  type: string
            example:
              "request": {"organizationalData": {"salesOrganization": "1000","distributionChannel": "10","division": "00"},"customerNumber": "0000001400","items": [{"number": "000010","material": "P-106","plant": "1000","quantity": "001","category": "TAN","schedules": [{"line": "0001","quantity": "001"}]}]}
      responses:
        "201":
          description: Success
          content:
            "application/json":
              schema:
                type: object
                properties: 
                  response:
                    type: object
                    properties: 
                      number:
                        type: string
                      messages:
                        type: array
                        items:
                          type: object
                          properties: 
                            content:
                              type: string
                      message:
                        type: string